version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'Anderson'
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: aluguel_de_carros
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - my-network

networks:
  my-network:

volumes:
  postgres_data:
